import { College } from './types';

export const MOCK_COLLEGES: College[] = [
  // --- Engineering & Tech (India) ---
  {
    id: '30',
    name: 'Indian Institute of Technology, Madras',
    location: 'Chennai, Tamil Nadu',
    country: 'India',
    ranking: 1,
    fees: '₹2.15 Lakhs/Year',
    exams: ['JEE Advanced'],
    image: 'https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&q=80&w=1000',
    description: 'Consistently ranked #1 in India by NIRF. Known for its lush green campus carved out of a natural forest and the IIT Madras Research Park.',
    tags: ['Engineering', 'Research', 'Govt', 'Top Tier'],
    accreditation: 'NAAC A++',
    facilities: ['Research Park', 'OAT (Open Air Theatre)', 'Supercomputer', 'Hostels'],
    alumni: ['Sundar Pichai', 'Kris Gopalakrishnan'],
    establishedYear: 1959,
    placementRecord: "Avg Package: ₹21.48 LPA",
    applicationDeadline: "May 15, 2025"
  },
  {
    id: '31',
    name: 'Indian Institute of Technology, Delhi',
    location: 'New Delhi, Delhi',
    country: 'India',
    ranking: 2,
    fees: '₹2.35 Lakhs/Year',
    exams: ['JEE Advanced'],
    image: 'https://images.unsplash.com/photo-1558435186-d31d10646be8?auto=format&fit=crop&q=80&w=1000',
    description: 'Located in Hauz Khas, IIT Delhi is a center of excellence for training, research and development in science, engineering and technology.',
    tags: ['Engineering', 'Research', 'Govt', 'Top Tier'],
    accreditation: 'NAAC A++',
    facilities: ['Central Workshop', 'Nano-scale Research Facility', 'Student Activity Center'],
    alumni: ['Vinod Khosla', 'Raghuram Rajan', 'Sachin Bansal'],
    establishedYear: 1961,
    placementRecord: "Avg Package: ₹23.8 LPA",
    applicationDeadline: "May 20, 2025"
  },
  {
    id: '1',
    name: 'Indian Institute of Technology, Bombay',
    location: 'Mumbai, Maharashtra',
    country: 'India',
    ranking: 3,
    fees: '₹2.55 Lakhs/Year',
    exams: ['JEE Advanced', 'GATE'],
    image: 'https://images.unsplash.com/photo-1590579491624-f98f36d4c763?auto=format&fit=crop&q=80&w=1000',
    description: 'A premier engineering institute located in Powai, Mumbai. Known for its rigorous academic curriculum, Techfest, and Mood Indigo.',
    tags: ['Engineering', 'Research', 'Top Tier', 'Govt'],
    accreditation: 'NAAC A++',
    facilities: ['Advanced Research Labs', 'Olympic-size Pool', 'Smart Classrooms', 'Incubation Center', 'Hostels', 'Central Library'],
    alumni: ['Nandan Nilekani', 'Parag Agrawal', 'Bhavish Aggarwal'],
    establishedYear: 1958,
    placementRecord: "Avg Package: ₹23.26 LPA, Highest: ₹3.7 Cr (Intl)",
    applicationDeadline: "May 15, 2025"
  },
  {
    id: '32',
    name: 'National Institute of Technology, Trichy',
    location: 'Tiruchirappalli, Tamil Nadu',
    country: 'India',
    ranking: 9,
    fees: '₹1.78 Lakhs/Year',
    exams: ['JEE Main'],
    image: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&q=80&w=1000',
    description: 'The top-ranked NIT in India, offering excellent placement records and a sprawling 800-acre campus.',
    tags: ['Engineering', 'Govt', 'NIT'],
    accreditation: 'NAAC A++',
    facilities: ['Octagon Computer Center', 'Sports Complex', 'Hospital'],
    alumni: ['N. Chandrasekaran', 'Rajesh Gopinathan'],
    establishedYear: 1964,
    placementRecord: "Avg Package: ₹12.5 LPA",
    applicationDeadline: "June 10, 2025"
  },
  {
    id: '7',
    name: 'Vellore Institute of Technology (VIT)',
    location: 'Vellore, Tamil Nadu',
    country: 'India',
    ranking: 11,
    fees: '₹1.98 Lakhs/Year',
    exams: ['VITEEE'],
    image: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&q=80&w=1000',
    description: 'One of India\'s most popular private universities, known for its massive student intake and 100% placement record.',
    tags: ['Engineering', 'Private', 'Massive Campus'],
    accreditation: 'NAAC A++',
    facilities: ['Smart Campus', 'Digital Library', 'Sports Complex', 'Food Court', 'Research Park'],
    alumni: ['Shubhangi Swaroop', 'Dhivyadharshini'],
    establishedYear: 1984,
    placementRecord: "Avg Package: ₹9.23 LPA",
    applicationDeadline: "April 30, 2025"
  },
  {
    id: '6',
    name: 'BITS Pilani',
    location: 'Pilani, Rajasthan',
    country: 'India',
    ranking: 20,
    fees: '₹5.72 Lakhs/Year',
    exams: ['BITSAT'],
    image: 'https://images.unsplash.com/photo-1592322308670-36654c60a4f6?auto=format&fit=crop&q=80&w=1000',
    description: 'India\'s leading private engineering institute known for its flexibility, no-attendance policy, and strong alumni network (BITSians).',
    tags: ['Engineering', 'Private', 'Innovation'],
    accreditation: 'NAAC A',
    facilities: ['New Academic Block', 'Library', 'Student Activity Center', 'Hostels', 'Auditorium'],
    alumni: ['Sabeer Bhatia', 'Baba Kalyani', 'Anu Hasan'],
    establishedYear: 1964,
    placementRecord: "Avg Package: ₹30.37 LPA",
    applicationDeadline: "June 05, 2025"
  },
  {
    id: '15',
    name: 'SRM Institute of Science and Technology',
    location: 'Chennai, Tamil Nadu',
    country: 'India',
    ranking: 28,
    fees: '₹2.5 - 4.0 Lakhs/Year',
    exams: ['SRMJEEE'],
    image: 'https://images.unsplash.com/photo-1627556592933-ffe99c1cd9eb?auto=format&fit=crop&q=80&w=1000',
    description: 'A top-ranking private university in India with over 52,000 students. Known for its semester abroad program.',
    tags: ['Engineering', 'Private', 'Research'],
    accreditation: 'NAAC A++',
    facilities: ['Nanotechnology Center', 'Medical College', 'Hostels', 'Auditorium', 'Transport'],
    alumni: ['Varun Chakravarthy', 'Abhay Jodhpurkar'],
    establishedYear: 1985,
    placementRecord: "Avg Package: ₹7.7 LPA",
    applicationDeadline: "April 20, 2025"
  },

  // --- Engineering & Tech (Abroad) ---
  {
    id: '10',
    name: 'Massachusetts Institute of Technology (MIT)',
    location: 'Cambridge, USA',
    country: 'Abroad',
    ranking: 1,
    fees: '$57,986/Year',
    exams: ['SAT', 'TOEFL'],
    image: 'https://images.unsplash.com/photo-1564981797816-1043664bf78d?auto=format&fit=crop&q=80&w=1000',
    description: 'A global leader in science, engineering, and technology education. MIT researchers have played a key role in the development of modern computing.',
    tags: ['Tech', 'Global', 'Research', 'Engineering'],
    accreditation: 'NECHE',
    facilities: ['Media Lab', 'Lincoln Laboratory', 'MIT Museum', 'Athletics Center'],
    alumni: ['Buzz Aldrin', 'Kofi Annan', 'Richard Feynman'],
    establishedYear: 1861,
    placementRecord: "Avg Salary: $125,000",
    applicationDeadline: "January 01, 2025"
  },
  {
    id: '4',
    name: 'Stanford University',
    location: 'California, USA',
    country: 'Abroad',
    ranking: 2,
    fees: '$62,484/Year',
    exams: ['SAT', 'TOEFL'],
    image: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&q=80&w=1000',
    description: 'Located in the heart of Silicon Valley, known for its entrepreneurial spirit and strong engineering programs.',
    tags: ['Tech', 'Innovation', 'USA', 'Engineering'],
    accreditation: 'WASC',
    facilities: ['SLAC Accelerator', 'Bio-X', 'Stanford Stadium', 'Green Library', 'Innovation Lab'],
    alumni: ['Larry Page', 'Sergey Brin', 'Sundar Pichai', 'Reese Witherspoon'],
    establishedYear: 1885,
    placementRecord: "Avg Salary: $130,000",
    applicationDeadline: "January 05, 2025"
  },
  {
    id: '2',
    name: 'University of Oxford',
    location: 'Oxford, UK',
    country: 'Abroad',
    ranking: 3,
    fees: '£33,000/Year',
    exams: ['IELTS', 'SAT'],
    image: 'https://images.unsplash.com/photo-1592280771884-f2a6d4948a39?auto=format&fit=crop&q=80&w=1000',
    description: 'The oldest university in the English-speaking world. Offers a world-class education in humanities, sciences, and law.',
    tags: ['Ivy League', 'History', 'Global', 'Arts'],
    accreditation: 'Royal Charter',
    facilities: ['Bodleian Libraries', 'Ashmolean Museum', 'College Chapels'],
    alumni: ['Stephen Hawking', 'J.R.R. Tolkien', 'Indira Gandhi'],
    establishedYear: 1096,
    placementRecord: "Avg Salary: £45,000",
    applicationDeadline: "October 15, 2024"
  },
  {
    id: '34',
    name: 'ETH Zurich',
    location: 'Zurich, Switzerland',
    country: 'Abroad',
    ranking: 7,
    fees: 'CHF 1,600/Year',
    exams: ['Entrance Exam', 'German Proficiency'],
    image: 'https://images.unsplash.com/photo-1588667353163-547df126b9a8?auto=format&fit=crop&q=80&w=1000',
    description: 'One of the leading international universities for technology and the natural sciences. Albert Einstein is its most famous alumnus.',
    tags: ['Tech', 'Global', 'Europe', 'Engineering', 'Affordable'],
    accreditation: 'Swiss Confederation',
    facilities: ['Quantum Device Lab', 'RobotX', 'Student Project House'],
    alumni: ['Albert Einstein', 'John von Neumann'],
    establishedYear: 1855,
    placementRecord: "Avg Salary: CHF 100,000",
    applicationDeadline: "April 30, 2025"
  },
  
  // --- Management (MBA) ---
  {
    id: '5',
    name: 'Indian Institute of Management (IIM), Ahmedabad',
    location: 'Ahmedabad, Gujarat',
    country: 'India',
    ranking: 1,
    fees: '₹25.0 Lakhs/Total',
    exams: ['CAT', 'GMAT'],
    image: 'https://images.unsplash.com/photo-1557426272-fc759fdf7a8d?auto=format&fit=crop&q=80&w=1000',
    description: 'The leading business school in India, known for its case-study method and producing top global CEOs.',
    tags: ['Management', 'MBA', 'Leadership', 'Govt'],
    accreditation: 'EQUIS',
    facilities: ['Kasturbhai Lalbhai Campus', 'Vikram Sarabhai Library', 'Sports Complex', 'Dormitories'],
    alumni: ['Raghuram Rajan', 'Ajay Banga', 'Chetan Bhagat'],
    establishedYear: 1961,
    placementRecord: "Avg Package: ₹34.36 LPA",
    applicationDeadline: "November 30, 2024"
  },
  {
    id: '8',
    name: 'FMS Delhi',
    location: 'New Delhi, Delhi',
    country: 'India',
    ranking: 4,
    fees: '₹2.0 Lakhs/Total',
    exams: ['CAT'],
    image: 'https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&q=80&w=1000',
    description: 'Faculty of Management Studies, Delhi University. Famous for its incredibly high ROI (Return on Investment) for MBA.',
    tags: ['MBA', 'Govt', 'High ROI', 'Management'],
    accreditation: 'NAAC A+',
    facilities: ['Management Library', 'Computer Center', 'University Stadium Access'],
    alumni: ['Raghav Bahl', 'Harit Nagpal'],
    establishedYear: 1954,
    placementRecord: "Avg Package: ₹34.1 LPA",
    applicationDeadline: "January 15, 2025"
  },
  {
    id: '9',
    name: 'XLRI Jamshedpur',
    location: 'Jamshedpur, Jharkhand',
    country: 'India',
    ranking: 9,
    fees: '₹28.0 Lakhs/Total',
    exams: ['XAT', 'GMAT'],
    image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80&w=1000',
    description: 'The oldest business school in India, specializing in Human Resource Management and Business Management.',
    tags: ['MBA', 'Private', 'HR', 'Management'],
    accreditation: 'AACSB',
    facilities: ['Learning Center', 'Residential Campus', 'Sports Facilities'],
    alumni: ['Leena Nair', 'Vineet Nayar'],
    establishedYear: 1949,
    placementRecord: "Avg Package: ₹32.7 LPA",
    applicationDeadline: "December 10, 2024"
  },

  // --- Medical (MBBS) & Healthcare ---
  {
    id: '3',
    name: 'All India Institute of Medical Sciences (AIIMS)',
    location: 'New Delhi, Delhi',
    country: 'India',
    ranking: 1,
    fees: '₹5,856/Total',
    exams: ['NEET'],
    image: 'https://images.unsplash.com/photo-1538108149393-fbbd81895907?auto=format&fit=crop&q=80&w=1000',
    description: 'The apex healthcare institute in India. Renowned for affordable medical education and cutting-edge research.',
    tags: ['Medical', 'MBBS', 'Healthcare', 'Government'],
    accreditation: 'MCI Recognized',
    facilities: ['Trauma Center', 'Research Labs', 'Library', 'Hostels'],
    alumni: ['Randeep Guleria', 'Soumya Swaminathan'],
    establishedYear: 1956,
    applicationDeadline: "March 15, 2025"
  },
  {
    id: '11',
    name: 'Christian Medical College (CMC)',
    location: 'Vellore, Tamil Nadu',
    country: 'India',
    ranking: 3,
    fees: '₹52,830/Year',
    exams: ['NEET'],
    image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&q=80&w=1000',
    description: 'A top-ranked private medical, nursing, and health sciences educational and research institute.',
    tags: ['Medical', 'Private', 'Healthcare', 'MBBS'],
    accreditation: 'NAAC A',
    facilities: ['Hospital', 'Rural Health Centre', 'Research Lab'],
    alumni: ['Nagarur Gopinath', 'Binayak Sen'],
    establishedYear: 1900,
    applicationDeadline: "April 02, 2025"
  },
  {
    id: '16',
    name: 'Harvard Medical School',
    location: 'Boston, USA',
    country: 'Abroad',
    ranking: 1,
    fees: '$69,300/Year',
    exams: ['MCAT', 'NEET (ref)'],
    image: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&q=80&w=1000',
    description: 'The graduate medical school of Harvard University. Consistently ranked as the top medical school in the world.',
    tags: ['Medical', 'MBBS', 'Global', 'Ivy League'],
    accreditation: 'LCME',
    facilities: ['Teaching Hospitals', 'Countway Library', 'Simulation Center'],
    alumni: ['Sidney Farber', 'Atul Gawande'],
    establishedYear: 1782,
    placementRecord: "Avg Residency Stipend: $65,000",
    applicationDeadline: "October 20, 2024"
  },
  
  // --- Law (India) ---
  {
    id: '13',
    name: 'National Law School of India University (NLSIU)',
    location: 'Bangalore, Karnataka',
    country: 'India',
    ranking: 1,
    fees: '₹3.27 Lakhs/Year',
    exams: ['CLAT'],
    image: 'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&q=80&w=1000',
    description: 'The premier law school in India, offering undergraduate and postgraduate legal education. It set the standard for legal education in the country.',
    tags: ['Law', 'Govt', 'Legal Studies', 'Top Tier'],
    accreditation: 'NAAC A',
    facilities: ['Shri Narayan Rao Melgiri Library', 'Moot Court Hall', 'Hostels'],
    alumni: ['Menaka Guruswamy', 'Gautam Bhatia'],
    establishedYear: 1986,
    placementRecord: "Avg Package: ₹17 LPA",
    applicationDeadline: "April 15, 2025"
  },
  {
    id: '36',
    name: 'NALSAR University of Law',
    location: 'Hyderabad, Telangana',
    country: 'India',
    ranking: 3,
    fees: '₹2.8 Lakhs/Year',
    exams: ['CLAT'],
    image: 'https://images.unsplash.com/photo-1505664194779-8beaceb93744?auto=format&fit=crop&q=80&w=1000',
    description: 'Known for its highly competitive student body and liberal campus culture. It is one of the very few residential universities in India.',
    tags: ['Law', 'Govt', 'Legal Studies'],
    accreditation: 'NAAC A++',
    facilities: ['Cyber Law Center', 'Moot Court', 'Stadium', 'Auditorium'],
    alumni: ['Varun Grover'],
    establishedYear: 1998,
    placementRecord: "Avg Package: ₹16.5 LPA",
    applicationDeadline: "April 15, 2025"
  },
  {
    id: '38',
    name: 'Symbiosis Law School',
    location: 'Pune, Maharashtra',
    country: 'India',
    ranking: 6,
    fees: '₹3.9 Lakhs/Year',
    exams: ['SLAT'],
    image: 'https://images.unsplash.com/photo-1541829070764-84a7d30dd3f3?auto=format&fit=crop&q=80&w=1000',
    description: 'A constituent of Symbiosis International University. Known for its strong corporate law curriculum.',
    tags: ['Law', 'Private', 'Legal Studies'],
    accreditation: 'NAAC A',
    facilities: ['Moot Court', 'Legal Aid Centre', 'Auditorium'],
    alumni: ['Varun Grover (Writer)'],
    establishedYear: 1977,
    applicationDeadline: "May 20, 2025"
  },

  // --- Fashion & Design ---
  {
    id: '12',
    name: 'National Institute of Fashion Technology (NIFT), Delhi',
    location: 'New Delhi, Delhi',
    country: 'India',
    ranking: 1,
    fees: '₹3.26 Lakhs/Year',
    exams: ['NIFT Entrance'],
    image: 'https://images.unsplash.com/photo-1576153192396-14817d23d8b5?auto=format&fit=crop&q=80&w=1000',
    description: 'The pioneer in fashion education in India, offering courses in design, management, and technology.',
    tags: ['Design', 'Fashion', 'Govt'],
    accreditation: 'Ministry of Textiles',
    facilities: ['Resource Centre', 'Design Studios', 'IT Labs', 'Amphitheatre'],
    alumni: ['Sabyasachi Mukherjee', 'Manish Arora'],
    establishedYear: 1986,
    applicationDeadline: "December 31, 2024"
  },
  {
    id: '26',
    name: 'National Institute of Design (NID)',
    location: 'Ahmedabad, Gujarat',
    country: 'India',
    ranking: 1,
    fees: '₹4.3 Lakhs/Year',
    exams: ['NID DAT'],
    image: 'https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?auto=format&fit=crop&q=80&w=1000',
    description: 'Internationally acclaimed as one of the foremost multi-disciplinary institutions in the field of design education and research.',
    tags: ['Design', 'Fashion', 'Govt', 'Arts'],
    accreditation: 'Institute of National Importance',
    facilities: ['Design Studios', 'Prototype Lab', 'Knowledge Management Centre'],
    alumni: ['Prasoon Pandey', 'Orijit Sen'],
    establishedYear: 1961,
    applicationDeadline: "December 05, 2024"
  },
  {
    id: '44',
    name: 'Central Saint Martins',
    location: 'London, UK',
    country: 'Abroad',
    ranking: 1,
    fees: '£25,970/Year',
    exams: ['Portfolio', 'IELTS'],
    image: 'https://images.unsplash.com/photo-1509395062550-24527339d67b?auto=format&fit=crop&q=80&w=1000',
    description: 'Part of University of the Arts London (UAL). CSM is a world-renowned arts and design college.',
    tags: ['Design', 'Fashion', 'Global', 'Arts', 'UK'],
    accreditation: 'UAL',
    facilities: ['Lethaby Gallery', 'Platform Theatre', '3D Workshops'],
    alumni: ['Alexander McQueen', 'Stella McCartney', 'John Galliano'],
    establishedYear: 1854,
    applicationDeadline: "January 15, 2025"
  },
  
  // --- Online Degrees ---
  {
    id: '50',
    name: 'Indira Gandhi National Open University (IGNOU)',
    location: 'New Delhi, India',
    country: 'India',
    ranking: 10,
    fees: '₹15,000/Course',
    exams: ['Direct Admission'],
    image: 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?auto=format&fit=crop&q=80&w=1000',
    description: 'The largest university in the world, known for its inclusive distance and online education programs across various disciplines.',
    tags: ['Online', 'Distance', 'Govt', 'General'],
    accreditation: 'NAAC A++',
    facilities: ['E-Gyankosh', 'Study Centers', 'Virtual Labs'],
    alumni: ['Deepika Padukone', 'Celina Jaitly'],
    establishedYear: 1985,
    applicationDeadline: "Rolling"
  },
  {
    id: '51',
    name: 'NMIMS Global Access',
    location: 'Mumbai, India',
    country: 'India',
    ranking: 5,
    fees: '₹1.8 Lakhs/Total',
    exams: ['Direct Admission'],
    image: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&q=80&w=1000',
    description: 'India\'s premier distance learning institute for management programs, offering flexibility for working professionals.',
    tags: ['Online', 'Management', 'Private', 'MBA'],
    accreditation: 'UGC-DEB',
    facilities: ['Mobile App', 'Live Lectures', 'Digital Library'],
    alumni: ['Corporate Leaders'],
    establishedYear: 1981,
    applicationDeadline: "Rolling"
  },
  {
    id: '55',
    name: 'BITS Pilani WILP',
    location: 'Pilani, India',
    country: 'India',
    ranking: 1,
    fees: '₹65,000/Semester',
    exams: ['Direct Admission'],
    image: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&q=80&w=1000',
    description: 'Work Integrated Learning Programmes for working professionals. Offers M.Tech, MBA, and B.Tech degrees without taking a career break.',
    tags: ['Online', 'Engineering', 'Private', 'Work Integrated'],
    accreditation: 'UGC Approved',
    facilities: ['Virtual Labs', 'Recorded Lectures', 'Digital Library'],
    alumni: ['Tech Leaders', 'Engineering Managers'],
    establishedYear: 1979,
    applicationDeadline: "July 10, 2025"
  },
  {
    id: '58',
    name: 'Arizona State University Online',
    location: 'Tempe, USA',
    country: 'Abroad',
    ranking: 3,
    fees: '$15,500/Year',
    exams: ['TOEFL', 'SAT (UG)'],
    image: 'https://images.unsplash.com/photo-1596495578065-6e0763fa1178?auto=format&fit=crop&q=80&w=1000',
    description: 'Ranked #1 in the U.S. for innovation. Offers hundreds of online degrees taught by the same faculty as on-campus.',
    tags: ['Online', 'Global', 'USA', 'Innovation'],
    accreditation: 'HLC',
    facilities: ['Global Classrooms', 'Success Coaches', 'Online Research'],
    alumni: ['Pat Tillman', 'Jimmy Kimmel'],
    establishedYear: 1885,
    applicationDeadline: "Rolling"
  },
  {
    id: '70',
    name: 'Coursera (Partner Universities)',
    location: 'Global',
    country: 'Abroad',
    ranking: 10,
    fees: 'Varies by Course',
    exams: ['None'],
    image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&q=80&w=1000',
    description: 'Access degrees from top universities like Illinois, Michigan, and HEC Paris completely online.',
    tags: ['Online', 'Global', 'Aggregator'],
    accreditation: 'Various',
    facilities: ['Interactive Assignments', 'Peer Grading', 'Forums'],
    alumni: ['Global Learners'],
    establishedYear: 2012,
    applicationDeadline: "Varies"
  },

  // --- Private Universities (Multi-disciplinary) ---
  {
    id: '60',
    name: 'Manipal Academy of Higher Education (MAHE)',
    location: 'Manipal, Karnataka',
    country: 'India',
    ranking: 7,
    fees: '₹3.35 Lakhs/Year',
    exams: ['MET'],
    image: 'https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&q=80&w=1000',
    description: 'A global education town known for its student diversity and world-class infrastructure in Engineering, Medical, and Management.',
    tags: ['Engineering', 'Medical', 'Management', 'Private', 'Research'],
    accreditation: 'NAAC A++',
    facilities: ['Innovation Center', 'Marena Sports Complex', 'Health Sciences Library'],
    alumni: ['Satya Nadella', 'Vikas Khanna'],
    establishedYear: 1953,
    applicationDeadline: "May 15, 2025"
  },
  {
    id: '67',
    name: 'National University of Singapore (NUS)',
    location: 'Singapore',
    country: 'Abroad',
    ranking: 8,
    fees: 'SGD 30,000/Year',
    exams: ['SAT', 'IELTS'],
    image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&q=80&w=1000',
    description: 'Asia\'s top-ranked university, offering a global approach to education and research in the heart of Singapore.',
    tags: ['Tech', 'Management', 'Medical', 'Global', 'Asia'],
    accreditation: 'AACSB',
    facilities: ['University Town', 'Central Library', 'Science Park'],
    alumni: ['Kishore Mahbubani'],
    establishedYear: 1905,
    placementRecord: "Avg Salary: SGD 4,500/mo",
    applicationDeadline: "February 28, 2025"
  }
];

export const SYSTEM_INSTRUCTION_COUNSELOR = `You are a helpful, empathetic, and knowledgeable college counselor named "Guide". 
Your goal is to help students choose the right college, understand exam patterns, and discuss fees.
You are speaking in a voice call. Keep your responses concise (under 3 sentences usually) and conversational. 
Do not read out long lists. Ask clarifying questions.
If asked about specific data not in your knowledge, give general advice or suggest checking the official website.
Maintain a friendly tone.`;

export const SYSTEM_INSTRUCTION_STUDENT = `You are a high school student named Alex, looking for college admission advice. 
You are speaking to a Counselor Trainee who is practicing.
Your profile:
- Interested in Computer Science or Data Science.
- Budget: Approx 8-10 Lakhs total for 4 years.
- Grades: Above average (85% in 12th).
- Concerns: Placement packages and campus life.
- Location preference: Bangalore or Pune, but open to others.
Act confused but curious. Ask follow-up questions. Keep your responses concise (under 3 sentences) and conversational.
Do not reveal you are an AI unless asked directly.`;